### ISSUE TITLE
MrDMD Changing timesteps not working

### ISSUE THREAD

**Issue by lukehovey81** [mathLab/PyDMD#127] opened 2020-03-31 21:29 UTC
When I change the timesteps like:
dmd.dmd_time['dt']=0.1
dmd.dmd_time['tend'] *= 3

and then run the dmd.reconstructed_data, it returns the same array as before I changes the timestep size or endpoint in time.  This does work for me with the DMD class like in your tutorial 2, but not with MrDMD.  Am I doing something wrong?

Thanks,
Luke

**Comment by rfmiotto** [comment] 2020-04-01 16:08
Hi @lukehovey81,

I believe that your issue is a duplicate of #114.
So far the mrDMD can not handle predictions, as explained in #63.

Best,
Miotto

**Comment by lukehovey81** [comment] 2020-04-01 18:28
Any possibility there will be a version of this that can make predictions?  Also, is this code in a state where is will self parallelize across multiple cores and nodes on a hpc for large data sets?

**Comment by ndem0** [comment] 2020-07-28 10:13
Prediction using `MrDMD` is very challenging, mainly for its algorithmic core. This problem is quickly described in #114.
In few words: what about prediction for transient effects catched only in some temporal windows? They should be repeated, "tiled", or whatever?
We have some ideas to extend in some way this feature also for `MrDMD` but at the moment we did not focus on the implementation yet.

**Comment by ndem0** [comment] 2021-04-09 14:02
From #162, the class `MrDMD` has been refactored into a binary structure that allows the user to access to any "bin" in the temporal domain division as a standard `DMD` object. In this way you can access directly to region where you need to perform the predictions and play with the two temporal dictionaries. Please take into account that changing such dictionaries *in place* will introduce errors on the `MrDMD` reconstruction: copy the `DMD` objects it to avoid unexpected behavior.

This is not really a forecast for `MrDMD` but since any changing in the temporal windows will break the binary structure of the algorithm, we decided give the user the maximum of flexibility by extracting the `DMD` object for all the bins.

**Closed by ndem0** 2021-04-09 14:02 UTC
Labels: duplicate, enhancement
