### ISSUE TITLE
MrDMD+HODMD use case issues

### ISSUE THREAD

**Issue by MSchmidt99** [mathLab/PyDMD#251] opened 2022-03-08 05:00 UTC
**Describe the bug**
When attempting a multi-resolution higher order DMD there are matrix size issues. The initial issue can be skirted by swapping `hodmd._compute_amplitudes` for `hodmd._sub_dmd._compute_amplitudes`, however that will uncover further dimension errors down the line.

**To Reproduce**
```
stock1_df = pd.read_csv("path/to/AAPL.csv") # open/high/low/close/volume time series format
log_series = np.log(stock1_df['Close'])
log_series /= log_series.values[-1]

hodmd1 = HODMD(opt=True, d=20)
hodmd1._compute_amplitudes = hodmd1._sub_dmd._compute_amplitudes
mrdmd1 = MrDMD(hodmd1, max_level=6, max_cycles=8).fit(log_series.values)
```

**Output**
```
ValueError                                Traceback (most recent call last)
<ipython-input-31-04894394d9bf> in <module>
      1 hodmd1 = HODMD(opt=True, d=20)
      2 hodmd1._compute_amplitudes = hodmd1._sub_dmd._compute_amplitudes
----> 3 mrdmd1 = MrDMD(hodmd1, max_level=6, max_cycles=10).fit(log_series.values)

C:\ProgramData\Anaconda3\lib\site-packages\pydmd\mrdmd.py in fit(self, X)
    395             for leaf, x in enumerate(Xs):
    396                 current_dmd = self.dmd_tree[level, leaf]
--> 397                 current_dmd.fit(x)
    398 
    399                 rho = old_div(float(self.max_cycles), x.shape[1])

C:\ProgramData\Anaconda3\lib\site-packages\pydmd\hodmd.py in fit(self, X)
    135         snp = self.U_extra.T.dot(org_snp)
    136 
--> 137         super().fit(snp)
    138         self._snapshots_shape = snapshots_shape
    139         self._snapshots = org_snp

C:\ProgramData\Anaconda3\lib\site-packages\pydmd\hankeldmd.py in fit(self, X)
    326         """
    327         snp, self._snapshots_shape = self._col_major_2darray(X)
--> 328         self._snapshots = self._pseudo_hankel_matrix(snp)
    329         self._sub_dmd.fit(self._snapshots)
    330 

C:\ProgramData\Anaconda3\lib\site-packages\pydmd\hankeldmd.py in _pseudo_hankel_matrix(self, X)
    263         return np.concatenate(
    264             [X[:, i : X.shape[1] - self.d + i + 1] for i in range(self.d)],
--> 265             axis=0,
    266         )
    267 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 13 and the array at index 3 has size 0
```

**Comment by fAndreuzzi** [comment] 2022-03-08 07:53
Hi @MSchmidt99, thank you for your report.

This is a minimal example to reproduce the issue (I'm removing some parameters and replacing `HODMD` with the simpler `HankelDMD`):
```python
import numpy as np
from pydmd import HankelDMD, MrDMD

# data
X = np.ones((5,20), dtype=float)
# error
MrDMD(HankelDMD(d=20)).fit(X)
```

Also, I noticed that when `d=5` there are no problems, but when `d=6` we have this error:
```python
>>> MrDMD(HankelDMD(d=6)).fit(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/francescoandreuzzi/Programming/SISSA/PyDMD/pydmd/mrdmd.py", line 396, in fit
    current_dmd.fit(x)
  File "/Users/francescoandreuzzi/Programming/SISSA/PyDMD/pydmd/hankeldmd.py", line 335, in fit
    self._sub_dmd.fit(self._snapshots)
  File "/Users/francescoandreuzzi/Programming/SISSA/PyDMD/pydmd/dmd.py", line 60, in fit
    self._snapshots, self._snapshots_shape = self._col_major_2darray(X)
  File "/Users/francescoandreuzzi/Programming/SISSA/PyDMD/pydmd/dmdbase.py", line 653, in _col_major_2darray
    cond_number = np.linalg.cond(snapshots)
  File "<__array_function__ internals>", line 5, in cond
  File "/usr/local/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1763, in cond
    raise LinAlgError("cond is not defined on empty arrays")
numpy.linalg.LinAlgError: cond is not defined on empty arrays
```

**Comment by fAndreuzzi** [comment] 2022-04-16 18:20
Hi @MSchmidt99, I think I managed to identify the problem. Setting `max_levels=6` in the constructor of `MrDMD` means that you are splitting your snapshots in progressively smaller time windows such that the smallest time window contains `N / 32` time instants. 

I don't know the measure of your dataset, but most likely you have `N / 32 < 20` (20 is the value you set for `d` in `HODMD`). This means that you don't have enough samples in your dataset for the parameters you're using.

### Fix
Just choose `max_levels` and `d` such that `N / 2^m >= d+1` (`m==max_levels`). The error message you got is indeed misleading, therefore I'll discuss with the team some possible improvements.

**Comment by fAndreuzzi** [comment] 2022-04-19 08:54
Hi @MSchmidt99, I opened two PRs (#259 and #260) to tackle this issue. Any feedback is welcome on both of these. I'm closing this issue since I think we took appropriate actions to fix it.

**Closed by fAndreuzzi** 2022-04-19 08:54 UTC
Labels: bug
